### ISSUE TITLE
Mention in the readme that trySkipIisCustomErrors="false" 

### ISSUE THREAD

**Issue by TimGeyssens** [dimi3tron/Umbraco.CustomErrors#2]
Currently not mentoined but for IIS to takeover the 404 you'll need to set trySkipIisCustomErrors="false" in the umbracosettings.config

**Comment by majdisorder** [comment]
Yes. That is correct. I'll update the docs with the next commit. Thanks for pointing it out

**Comment by majdisorder** [comment]
I hadn't mentioned it because the property is set to false per default in a new umbraco setup. Might be a hard one to figure out in existing installations, so i mentioned it in the docs.
